### ISSUE TITLE
IEEE 1685-2022 is available

### ISSUE THREAD

**Issue by ejd** [edaa-org/IPXACT-Schema#1]
The schema files for IEEE 1685-2022 were released recently.  You may want to include them in this repo.

http://www.accellera.org/XMLSchema/IPXACT/1685-2022/

**Comment by Paebbels** [comment]
On one hand, it's using Apache License, version 2.0. OTOH, each release contains a README, which has open source threatening rules.

Do you know any official statement of Accellera what license is used by IP-XACT?

**Comment by ejd** [comment]
Thank you for the quick turnaround!

**Comment by Paebbels** [comment]
@ejd are you using this repository from another repository or project?

If so, can I link you (please provide link and project name) on the README as a "consumer" similar to this: https://github.com/edaa-org/pyEDAA.CLITool#consumers

**Comment by Paebbels** [comment]
License issues have been resolved with Accellera.  
See [LinkedIn Post](https://www.linkedin.com/posts/patrick-lehmann-917a80144_404-activity-7087184423288197120-IL36)
